Repository UKHomeOffice/update-helmfile-action, pull requests merged in 2023-01, with the labels that each got.

#19 Update Readme with usage instructions
  README.md
Labels: skip-release

#22 ⬆️ Chore: Update deps
  package-lock.json
Labels: patch

#23 🧑‍💻 Migrate to TypeScript
  .eslintrc.js
  README.md
  babel.config.js
  dist/index.js
  dist/index.js.map
  dist/types.js
  package-lock.json
  package.json
  src/helpers.spec.ts
  src/helpers.ts
  src/index.js
  src/index.ts
  src/types.ts
  tsconfig.json
Labels: major
